### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by razArie** [timmolter/Sundial#27]
Hi,

I want to use Sundial for production scheduling where we have existing logic of mail forwarding.
In Sundial Job I am opening 19 threads to work with different inboxes, scheduling if of 10 minutes,
after ten minutes when Sundial Scheduler triggers the job i check in job if last job is not finished (by checking threads in ps command)  then just return.
this makes memory accumulation as job instance does not get removed,
what i am doing wrong?

Thanks to Tim for such a good open source,

Raz

**Comment by timmolter** [comment]
I suspect the issue might arise from the job creating it's own threads, but I'm not 100% sure.

Since each job already runs in its own thread, I always design them to not create more threads. So either the actions are run serially in the job one after the other or several jobs are scehuled to run in parallel.

If you want to start the scheuler with a bigger threadpool, use: `startScheduler(int threadPoolSize, String annotatedJobsPackageName)`.
